spring:
  application:
    name: builders-sas-api-reactive

  jackson:
    default-property-inclusion: non_empty

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/builders_sas_hexagonal
    username: postgres
    password: Leandro2009*

  sql:
    init:
      mode: never

server:
  port: 9090

logging:
  level:
    # üî• Ver solo errores REALES de tu API
    root: INFO
    com.builderssas: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG

    # üî• Mostrar errores de WebFlux (pero no todo Netty)
    org.springframework.r2dbc: ERROR
    reactor.netty.http.client: ERROR

    # ‚ùå Quitar ruido innecesario
    io.r2dbc.postgresql: ERROR
    reactor.netty: ERROR
